### PR TITLE
Majorly refactor the IPC

### PR DESCRIPTION
**Pull request by boofiboi**
this PR hopefully gets rid of the old green ass IPC for a hopefully more modern look (The color scheme isnt final, I just cant for god figure out a good colour combination.)

All features tested and working.

### CODE REVIEW

**Comment by boofiboi** [comment]
image
Preview of how it looks.

**Comment by MasterCatPL** [comment]
starttime is broken

**Comment by MasterCatPL** [comment]
Bruh

**Comment by rosne-gamingyt** [comment]
Nice, I'll test it and merge it soon.

**Comment by AssociatedWithN** [comment]
Pasters mane, ignore this SKID called MasterCatPL. He tried to rat me using wannacry, he also tried to DDoS my VPN.

**Comment by MasterCatPL** [comment]
> Pasters mane, ignore this SKID called MasterCatPL. He tried to rat me using wannacry, he also tried to DDoS my VPN.

Are you retarded?

**Comment by BigMacChomper63** [comment]
creatures-ov-deception-cool-skeleton

**Comment by boofiboi** [comment]
> > Pasters mane, ignore this SKID called MasterCatPL. He tried to rat me using wannacry, he also tried to DDoS my VPN.
> 
> Are you retarded?

you are

**Comment by AssociatedWithN** [comment]
> > Pasters mane, ignore this SKID called MasterCatPL. He tried to rat me using wannacry, he also tried to DDoS my VPN.
> 
> Are you retarded?

evil paster mad after getting exposed

**Pull request closed without merging**
