### PR TITLE
this fix was found on explowz cathook-ipc-web-panel

### PR DESCRIPTION
**Pull request by MasterCatPL**

### CODE REVIEW

**Comment by AssociatedWithN** [comment]
Paster... learn to code k1d, your DC is getting removed now.https://github.com/RosneBurgerworks/rosnehook-ipc-web-panel/assets/157900452/ca881c0b-9123-44b5-baec-a8d715cd6f7d

**Comment by MasterCatPL** [comment]
> Paster... learn to code k1d, your DC is getting removed now.https://github.com/RosneBurgerworks/rosnehook-ipc-web-panel/assets/157900452/ca881c0b-9123-44b5-baec-a8d715cd6f7d

idc

**Comment by AssociatedWithN** [comment]
Doesn't even work BTW

**Comment by MasterCatPL** [comment]
> Doesn't even work BTW

It works fine for me so stop lying

**Comment by AssociatedWithN** [comment]
Just because it works for you doesn't mean works for everybody.

**Comment by MasterCatPL** [comment]
> boo! wanker.

💀

**Pull request merged**
